name:                curl
version:             0.1.0.0
github:              "githubuser/curl"
license:             BSD3
author:              "mlrv"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  curl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - curl

tests:
  curl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - curl
